setup:
- type: timeout
  use_global_subscriber: true
  topics: 
  - name: /diag/node_infos
    callerids:
    - callerid: []
      timeout: 1.0
      max_timeouts_in_a_row: 2
  - name: /cam_front_bottom_left/image
    callerids:
    - callerid: []
      timeout: 2.0
      max_timeouts_in_a_row: 20 

#- type: activated
#  resource_topic: /diag/node_infos
#  nodes:
#  - name: /rs16_bl

- type: hz
  main_loop_rate: 1.0
  topics:
  - name: /cam_front_bottom_left/image
    callerids:
    - callerid: []
      filter:      
        type: mean
        window_size: 20
        deviation_type: std_deviation
      states:
      - state: 'ok'
        number: 0
        frequenzy:
          type: student_t
          true_mean: 0.085
          std_deviation: 0.003            # optional
          significance_level: 0.05   
#      - state: 'NOTok'
#        number: -1
#        frequenzy:
#          type: student_t
#          true_mean: 0.0
#          std_deviation: 0.01           # 0.08
#          significance_level: 0.05  
#



#- type: error_msg
#  nodes_of_interest: /xsens1/mtnode


